### ISSUE TITLE
Freelancer loses picture with game out of focus

### ISSUE THREAD

**Issue by shmerl** [AlpyneDreams/d8vk#113]
With current d8vk master (43f9208) and Wine 8.2 when running Freelancer and Alt-Tabbing out of the game for some period of time, the game turns black when it's refocused and then can't be restored and requires restarting it.

**Comment by WinterSnowfall** [comment]
Can confirm I've reproduced this with Wine Staging and latest master. When alt+tabbing back in while the problem is manifesting, I get a "compiling shaders..." message, the screen remains black and "Vidmem heap 0" usage slowly increases in constant increments (about 5MB per rendered frame as far as I can tell). 

I'll attempt to get the behavior on a trace, to figure out what is going on.

**Comment by WinterSnowfall** [comment]
@shmerl If you grab the [artifacts from PR 112](https://github.com/AlpyneDreams/d8vk/suites/11189044867/artifacts/571855147) and set `d3d8.allowNestedBeginScene = True` in a dxvk.conf file dropped alongside the game exe, does that fix it for you?

**Comment by WinterSnowfall** [comment]
I've collected two traces:
- one with d8vk: [freelancer.trace.tar.xz](https://drive.google.com/file/d/1SLd_eQMOW3860ELU9NjvV3mRWMfuteXh/view?usp=share_link)
- one with WineD3D: [freelancer.1.trace.tar.xz](https://drive.google.com/file/d/1AbxRpHrDW3ekSepAJdKGmqSRtLdSwjd_/view?usp=share_link)

Within the d8vk trace it's evident some calls to `BeginScene()` fail when the window is refocused (see frame 422) and the game gets stuck in a loop, calling `BeginScene()` over and over only to see it fail and try again, however those same calls succeed with WineD3D, because with WineD3D the game properly gets to call `EndScene()` before alt+tabbing out. This call to `EndScene()` before alt+tabbing out/unfocusing doesn't get to happen with d8vk for some reason.

The workaround I've suggested above should prevent that live loop, but is by no means a proper solution to the problem. The main issue at hand here is related to how d8vk/dxvk handles alt+tabbing.

**Comment by shmerl** [comment]
I tried that custom build and it still happens for me.

**Comment by WinterSnowfall** [comment]
> I tried that custom build and it still happens for me.

Do you see:
```
info:  Effective configuration:
info:    d3d8.allowNestedBeginScene = True
```
on launch?

I've tested it and can confirm it circumvents the issue for me, but it's only a workaround really.

**Comment by shmerl** [comment]
Oh, my bad, I think I forgot that config key. Can you please rebase your PR on the latest master? I wanted to try the static build to void having separate d3d9.dll.

**Comment by WinterSnowfall** [comment]
That would unfortunately be extremely painful and I'll only do it if I really have to. You'll notice I'm working with a fork of dxvk, not of d8vk directly, so yeah, thanks GitHub... besides, I'm not entirely sure how stable the static build is as of now, since it's very much a work in progress.

**Comment by shmerl** [comment]
Just tried it with conf file - seems to help me too.

**Comment by WinterSnowfall** [comment]
@shmerl Should now be fixed/worked around with latest master. Can you please retest?

P.S.: Statically linked builds are also working properly now :wink: .

**Comment by shmerl** [comment]
I'll test it shortly.

**Comment by shmerl** [comment]
I'll test it shortly.

How should I build it? Do I still need d3d9.dll or not anymore?

**Comment by Blisto91** [comment]
If you have the required dependencies https://github.com/AlpyneDreams/d8vk#requirements then you can just build like you would DXVK. But instead of using `package-release.sh` you instead use `build_d3d8.sh`.
Only a d3d8.dll is needed from d8vk now.

The easier way is to just grab the latest CI artifact from https://github.com/AlpyneDreams/d8vk/actions/workflows/artifacts.yml?query=branch%3Amain

**Comment by shmerl** [comment]
Yeah, I tried building it last time without d3d9.dll and something didn't work (I was using one from dxvk in the prefix). I'll give it another try now.

**Comment by shmerl** [comment]
Building with my own script, and I'm getting:

```
src/meson.build:36:4: ERROR: Problem encountered: D3D9 is required for D3D8.
```

I guess I'm doing something wrong.

That's how I'm calling it:

```
  meson setup --cross-file "$cross_file" --buildtype release --prefix "$dest_dir" --libdir "$lib_dir" --bindir "$lib_dir" -Denable_d3d9=false -Denable_d3d10=false -Denable_d3d11=false -Denable_dxgi=false "$build_dir"
```

**Comment by shmerl** [comment]
Oh, could be some branches mess. I see it switched to main from master, while dxvk didn't. I need to fix my script.

**Comment by shmerl** [comment]
Just tested - seems to work fine, thanks!

So I'll close this unless it comes up again.
