### ISSUE TITLE
Please add DXVK Async

### ISSUE THREAD

**Issue by klark231** [AlpyneDreams/d8vk#124]
Some games have noticeable improvement with dxvk async. please add it

**Comment by WinterSnowfall** [comment]
Please raise specific issues for d3d8 titles where you notice a large performance difference when comparing to native drivers, rather than being mysteriously vague.

Since "[I was there, Gandalf, 3000 years ago](https://www.youtube.com/watch?v=0cSW6qhLwio)", let me make clear that d3d8 is the first version of d3d to add support for programmable shaders, therefore shader use was minimal in most games at the time.

In fact, out of the ~120 d3d8 games I have installed in my development prefix only some 32-bit UE2 titles exhibit shader-compilation stutter, and that's because they are configured to provide support even for bottom tier hardware of the age (think Riva TNT2s). This is something one can easily solve by tweaking the engine to override these pointless limitations it's setting on itself.

That said, if there's ever a place in dxvk where the idea of having "dxvk-async" is completely useless, then it would be here.

**Comment by klark231** [comment]
> Please raise specific issues for d3d8 titles where you notice a large performance difference when comparing to native drivers, rather than being mysteriously vague.
> 
> Since "[I was there, Gandalf, 3000 years ago](https://www.youtube.com/watch?v=0cSW6qhLwio)", let me make clear that d3d8 is the first version of d3d to add support for programmable shaders, therefore shader use was minimal in most games at the time.
> 
> In fact, out of the ~120 d3d8 games I have installed in my development prefix only some 32-bit UE2 titles exhibit shader-compilation stutter, and that's because they are configured to provide support even for bottom tier hardware of the age (think Riva TNT2s). This is something one can easily solve by tweaking the engine to override these pointless limitations it's setting on itself.
> 
> That said, if there's ever a place in dxvk where the idea of having "dxvk-async" is completely useless, then it would be here.

ok one more thing why are there two zip file. what is the other with many .so what should I do with that

**Comment by Blisto91** [comment]
Thats dxvk native (d8vk in this case) to help developers who are interested have a easier time porting their games to Linux native without having to make a separate renderer if their game already is using Direct3D
