### ISSUE TITLE
The I of the Dragon - missing geometry

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#131]
The game is known to have some rendering issues even on Windows, however WineD3D seems to do better than d8vk in some regards, for example rendering all the bits of the flying rug under the prophet at the start of the first mission:

Here is d8vk:
![d8vk](https://user-images.githubusercontent.com/6306593/229310001-8c912509-467b-415e-b5f5-7cc133e262f2.png)

Here is WineD3D:
![WineD3D](https://user-images.githubusercontent.com/6306593/229309963-3c38eb59-0bdd-45a0-9225-0b26268b180b.png)

The problem is visible in the below trace.

### Software information
The I of the Dragon (GOG)

### System information
- GPU: RTX 3060
- Driver: 525.89.02
- Wine version: 8.5 Staging
- DXVK version: 2c56a1a

### Apitrace file(s)
[TheIOfTheDragon.trace.tar.xz](https://drive.google.com/file/d/1nv96M2nUctVEF2W8JDrTuu2pS9hNIwp_/view?usp=share_link)

### Log files
- d3d8.log: [TheIOfTheDragon_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11130406/TheIOfTheDragon_d3d8.log)

**Comment by WinterSnowfall** [comment]
It seems I spoke too soon. [This bit used to look good on Windows](https://youtu.be/CvhSA0aJ4Y4?list=PLvPGxXZPgG8PmNul0TpTF_uHcYhy1plMZ&t=413), at least at some point.

**Comment by dungeon007** [comment]
IDirect3DDevice8::ProcessVertices

Seems only DGVoodoo2 does them correct:
![tiotd](https://user-images.githubusercontent.com/49257090/229331486-6bbee9ad-f71a-4cec-ae71-cb5033b43ef6.png)

**Comment by WinterSnowfall** [comment]
Thank you for checking with dgVoodoo2 and confirming it works. That is actually good news. If there's missing functionality in d8vk's ProcessVertices when comparing to native drivers (or at least dgVoodoo2) and we can't rely on d3d9 to behave properly, then it's something we can look into adding.

It won't necessarily be a priority, since I don't think we've run across such problems in other games, but definitely something to keep in mind and address at some point.

**Comment by AlpyneDreams** [comment]
Notably, the log shows the game using unsupported render state `D3DRS_CLIPPING`. So it's possible that could be related, or not.

**Comment by AlpyneDreams** [comment]
It is indeed something ProcessVertices-related.

Source VB: (same FVF is set before ProcessVertices)
![image](https://github.com/AlpyneDreams/d8vk/assets/3376691/1d40c615-85ac-4aa2-9298-9dda10a0eb0a)

Dest VB: (same FVF is set before subsequent draw calls)
![image](https://github.com/AlpyneDreams/d8vk/assets/3376691/01c66a07-0881-499a-b7f7-b4dc9e62c052)

This second shader is actually the problem, as it's doing m_viewportInfo and xyz *= 1 / w transformation on the position when it should just passthrough the already-transformed position. Alternatively, maybe the real issue is with the FFVS used by ProcessVertices since it's an edge case using blend weights.

**Comment by AlpyneDreams** [comment]
Doesn't appear to only affect blended vertices. It's possible there may be behavior differences between d3d9 and d3d8 here in ProcessVertices but I'm not sure of that.

**Comment by AlpyneDreams** [comment]
I expect the best fix would be to test ProcessVertices on native D3D9 vs. native D3D8 vs. d9vk. If D3D8 and D3D9 are different then then I'd need to implement a workaround in d8vk, otherwise if d9vk is different then I'd need to change the behavior of d3d9 ProcessVertices/d3d9_swvp_emu to make it be the same. If they're all the same then there might be something wrong with how d9vk is handling XYZRHW.

**Comment by WinterSnowfall** [comment]
Now tracked here: https://github.com/doitsujin/dxvk/issues/4115
