### ISSUE TITLE
[Regression - MSVC?] Duke Nukem Forever 2001 is tryting to use an invalid pixel shader

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#134]
This is a good game for testing because it is so broken it really pushes edge cases. Obviously things are not quite right here and the game chugs like hell. There must have been a regression here.

[DukeForever_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11239615/DukeForever_d3d8.log)

**Comment by AlpyneDreams** [comment]
This one's quite ~~severe~~ acute as it's somehow got over 800 barriers and it just keeps increasing. It's sending the same value for pixel and vertex shader?? Tested on MSVC currently.

**Comment by AlpyneDreams** [comment]
It's possible it was an upstream regression or just one I can't find. Fortunately it might only affect MSVC so we'll have to test that.

**Comment by WinterSnowfall** [comment]
MSVC indeed. I've just tested it with mingw on main and it looks fine. The logs are also clean.

I can't seem to attack because my framerate's not high enough due to the whole NOOVERWRITE thing. What a game mechanic, eh?

Edit: Turns out I couldn't kick because I had skipped the intro. Shame on me, I guess.

**Comment by AlpyneDreams** [comment]
Yeah seems like this is fixed now even on MSVC. Game runs and looks fine (for what it is).
