### ISSUE TITLE
IGI 2: Covert Strike - FPS fluctuation

### ISSUE THREAD

**Issue by keenanweaver** [AlpyneDreams/d8vk#149]
### Software information
IGI 2 - Covert Strike

FPS starts roughly at 30 when starting the first level. Look at the ground to reach a much higher FPS (165 in my case). Go into the first building and see it increase above 30. Seems to be a distance thing. Decreased resolution to 1280x720 and had the same FPS following the same conditions.

Tried with WineD3D & dgVoodoo2; issue does not happen using those. I used the GOG & Zoom Platform versions of the game with the Bottles software.

### System information
- GPU: NVIDIA GeForce RTX 2080
- Driver: 530.41.03
- Wine version: kron4ek-wine-8.6-staging-tkg-amd64
- D8VK version: d8vk-v1.0-10cbd551f5277dca5a49bb171cf3c937fdd579d7

OS: NixOS 23.05 (Unstable)

### Apitrace file(s)
- [API Trace](https://www.mediafire.com/file/agzcwl2gm9jsdba/igi2-compressed.trace.tar.gz/file)

### Log files
- [igi2_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11437283/igi2_d3d8.log)

**Comment by AlpyneDreams** [comment]
Wow, that is quite bad. Thank you for your submission. 

Unfortunately, the trace runs bad on native d3d8 too, so this one will probably take a while to fix.  dgVoodoo 2 will be your best choice for the time being, I don't know what they're doing to make it run normally.

It seems like the game is doing a lot of tiny drawcalls with state changes in between (so our batcher can't fix it), and it's doing absolutely heinous-looking things with vertex buffers.

**Comment by AlpyneDreams** [comment]
Things that help:
- `d3d8.managedBufferPlacement=False` - This helps a lot here. (Keep allowDiscard=True, allowDBM=True)
- `d3d9.apitraceMode=True` - Marginally

I'm going to add these to the built-in configs, and that should make the game playable at least.

**Comment by AlpyneDreams** [comment]
The game should be playable now. Gonna leave this issue open for now because there might still be some improvements we can make for this game.

**Comment by dungeon007** [comment]
App dislikes any of IB/VB forced into managed pool. On d3d8to9 behave the same way, if i force any.
That was always mine experience with d3d8to9 too if i force any:
1. some likes one or another or both
2. some dislike one or another or both
3. some dont care
 These that dont care seems to be majority, but of course there are always some that do, more or less.
 Maybe because you are running big GPUs it might be harder to spot that always, that is why i test on slowest and oldest AMD APU, so that i could see any... 8 fps for me here :D
 
![igi2](https://github.com/AlpyneDreams/d8vk/assets/49257090/f0c1c48a-6084-4fdf-a7b2-6301c1759dcb)

**Comment by WinterSnowfall** [comment]
>  8 fps for me on d8vk 1.0.

That's interesting, because nothing is forced in 1.0 since managed placement was disabled via a config option - the game is doing whatever it likes with buffers.

**Comment by dungeon007** [comment]
Well, d8vk is the only one that forces both IB/VB into manaaged like that by default. So you can expect in some cases to go also bad more or less. 
 For example in Meet The Robinsons, 100 vs 60 fps
 d8vk 1.0
![1](https://github.com/AlpyneDreams/d8vk/assets/49257090/cd545e1a-1898-4161-b83e-c9663a3d67fc)
 d3d8to9 on d3d9 dxvk
![2](https://github.com/AlpyneDreams/d8vk/assets/49257090/74a1e941-671c-4e94-9d16-365ca93696f3)

 That not turn as bad as IGI2, perf looks playable, we can say even no one cares... but anyway, still shows you some potentional perf consenvences that could appear of such default here and there.
 And of course majority of apps do not care about this, but i guess any that goes clear negative on perf because of this, should probably carry on some profile, as who knows maybe there would be some scenes in such apps that could turn into going bad just like in IGI2...

**Comment by WinterSnowfall** [comment]
Doing more dynamic tuning around buffer placement is something we'll definitely look at, but as you aptly noted some game perform a bit worse with it, while others (based on some issues we had open) a lot worse without it. As of now it's sort of the lesser of evils, let's say.

P.S.: If you run across such games, do raise issues for them please.

**Comment by keenanweaver** [comment]
> Things that help:
> 
>     * `d3d8.managedBufferPlacement=False` - This helps a lot here. (Keep allowDiscard=True, allowDBM=True)
> 
>     * `d3d9.apitraceMode=True` - Marginally
> 
> 
> I'm going to add these to the built-in configs, and that should make the game playable at least.

Confirming from my end using these configs resolves the issue. Too bad D8VK can't fix the abysmal gameplay. Man, this game aged badly. 

Thank you all for looking into it! Excited for D8VK and its future.

(Also, WinterSnowfall, not sure if you remember me, but I'm 'Vagabond' on GOG. I recognized your name & avatar from somewhere!)

**Comment by dungeon007** [comment]
"P.S.: If you run across such games, do raise issues for them please."
 Sure, i think they are sort of rare actually, i just happans to remember some of them.

**Comment by WinterSnowfall** [comment]
> (Also, WinterSnowfall, not sure if you remember me, but I'm 'Vagabond' on GOG. I recognized your name & avatar from somewhere!)

I'd say "it's a small world", but I kind of knew GOG has a rather sizable community of Linux gamers :grin:. Anyway, enjoy your penguin-powered retro gaming! (I'd say d3d8 is retro enough by now.)


> **Wilbur.exe** is Meet The Robinsons exe name, hates IB/VB forces too. 

Thanks. I'll look into it and will probably add a workaround for it at some point.

**Comment by WinterSnowfall** [comment]
I think [this](https://github.com/doitsujin/dxvk/pull/3442) will most likely help here as well. Should recheck performance on the next rebase.

**Comment by WinterSnowfall** [comment]
I've retested the game after the rebase and it's perhaps somewhat better now (but no major improvements). Not sure if we need to keep this open, since the performance is fine now, all things considered.

**Comment by keenanweaver** [comment]
Working great on the latest artifact from the CI--no tweaks needed! Closing.
