### ISSUE TITLE
Use with DXVK 

### ISSUE THREAD

**Issue by Ilya114** [AlpyneDreams/d8vk#166]
Hi, it's possible use D8VK with DXVK? I mean D8VK using same environment variables as DXVK, so example `DXVK_CONFIG_FILE` can be apply for DXVK and D8VK simultaneously which can call conflicts. I want to see examplle `D8VK_CONFIG_FILE` instead of `DXVK_CONFIG_FILE`

**Comment by WinterSnowfall** [comment]
> Hi, it's possible use D8VK with DXVK? 

Yes, both can coexist in a Wine/Proton prefix.

> I mean D8VK using same environment variables as DXVK, so example `DXVK_CONFIG_FILE` can be apply for DXVK and D8VK simultaneously which can call conflicts. I want to see examplle `D8VK_CONFIG_FILE` instead of `DXVK_CONFIG_FILE`

While d8vk will load the config file specified in `DXVK_CONFIG_FILE` and take any d3d9 options into account, there shouldn't be any "conflicts", because d8vk uses dxvk's d3d9 backend. This behavior is more or less intended (and desirable) and will function similarly once d8vk is upstreamed/merged into dxvk.

P.S.: A game will NEVER use both d8vk and dxvk simultaneously.

**Comment by Ilya114** [comment]
I understand what I can use one configuration for D8VK and DXVK (Like DXVK_HUD and dxvk.conf) and it will work?

**Comment by WinterSnowfall** [comment]
> I understand what I can use one configuration for D8VK and DXVK (Like DXVK_HUD and dxvk.conf) and it will work?

Yes, same variables will be used for both. I am currently doing that in fact for configuring the HUD and log levels in both dxvk and d8vk.

**Comment by Ilya114** [comment]
Okay, thanks
