### ISSUE TITLE
Deer Hunter 2004 resolution change freeze

### ISSUE THREAD

**Issue by Blisto91** [AlpyneDreams/d8vk#174]
In Deer Hunter 2004 the rendering will freeze when you attempt to change the resolution in the video settings. This does not happen with wined3d

<details>
  <summary>Screenshot</summary>

![Screenshot_20230710_215002](https://github.com/AlpyneDreams/d8vk/assets/47954800/b95a6e05-9463-4218-82c4-ce4aaabdbbfb)
</details>

### Software information
Deer Hunter 2004 (Deer Hunger GOLD EDITION)

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton as the game crashes when entering video settings with regular Wine
- DXVK version: Latest main from artifacts

### Apitrace file(s)
https://drive.proton.me/urls/KJ0VXXBBVG#LjSTWdsn05Mb
One with wined3d where it works and one with d8vk where it gets stuck

### Log files
[DH2004_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/12006130/DH2004_d3d9.log)
[Game.LOG](https://github.com/AlpyneDreams/d8vk/files/12006131/Game.LOG)

**Comment by Blisto91** [comment]
Actually it just seems to happen any time it runs "changing video mode" which is also when you try to turn on FSAA

**Comment by Blisto91** [comment]
Didn't think to test PR https://github.com/AlpyneDreams/d8vk/pull/172 but it does indeed work with that as @WinterSnowFall suggested

**Comment by WinterSnowfall** [comment]
Two things might be interesting to look further into still, namely:
- `warn:  D3D9DeviceEx::SetClipStatus: Stub` (not sure if we actually want to implement that at some point, since [it looks like it's a SWVP exclusive thing](https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-setclipstatus)) - P.S.: WineD3D also stubs this, apparently, so it's most likely harmless.
- While playing back the WineD3D trace with d8vk, I get a lot of errors on IDirect3DVolume8 calls. But those could just be apitrace not grabbing some stuff properly, not entirely sure what's going on there, since the game renders just fine.

<details>
<summary>See here</summary>

![image](https://github.com/AlpyneDreams/d8vk/assets/6306593/034b1c2b-32ab-4267-a178-62e4f73d355c)

</details>

Edit: In retrospect, probably entirely closable once the PR is merged.
