### ISSUE TITLE
Error on start - MacOS and game porting toolkit

### ISSUE THREAD

**Issue by odqahn** [AlpyneDreams/d8vk#178]
### Software information
Trying to run FFXI with Ashita on MacOS via the game porting toolking. I don't really understand what I'm doing but it seems DXVK is there. I can run the game using dgVoodoo2 but for some reasons, I get a mixed result of really good perfs and lag, especially the sound that is stuttering.

Since dgVoodoo is translating Dx8 to Dx11, then game porting toolkit will translate again to Vulkan (am I correct?), I figured your project would be a more straightforward approach, probably helping improving a lot in perfs.

When starting the game, I get a message saying there's no adapter found. And I have no clue what I can do to fix that, or find logs.

I've attached a screen of the game running with dgVoodoo and the DXVK hub with all the infos, plus a screen of what's happening when trying to run the game.

Is there anything meaningful I could bring? Is my setup even in the scope of the project? Again, sorry for being so clueless and thank you in advance!

### System information
- GPU: M2 Max
- Driver: 0.2.2011
- Wine version: 7.7
- DXVK version: 1.10.3-20230507

### Screenshots
<img width="735" alt="Screenshot 2023-07-27 at 16 35 40" src="https://github.com/AlpyneDreams/d8vk/assets/26545834/c2a08273-9e5d-4dd1-856b-04e7e3553bdf">
<img width="1800" alt="Screenshot 2023-07-27 at 15 45 37" src="https://github.com/AlpyneDreams/d8vk/assets/26545834/aa59d6b7-3a57-4a78-b8a9-874622e6bf5a">

**Comment by WinterSnowfall** [comment]
> I've attached a screen of the game running with dgVoodoo and the DXVK hub with all the infos, plus a screen of what's happening when trying to run the game.

DXVK/D8VK need Vulkan 1.3 support at this point. It seems the porting toolkit only exposes 1.2 for some reason. I believe they will fully implement 1.3 at some point, after which things should probably work fine.

The porting toolkit might also natively support d3d8 at some point, which should make things a lot easier (meaning you won't need d8vk at all). I'm not sure where Apple plans to take it however, so take everything I say with a sack of salt (not only a grain :).

> Is my setup even in the scope of the project?

Not really in the scope, since nobody here is aiming to support MacOS, but that doesn't mean you can't use it as such. Just don't expect a lot of support if you run into issues, since nobody's really testing these things.

> Again, sorry for being so clueless and thank you in advance!

No worries. Everyone's clueless until they learn. It's nothing to apologize for.

**Comment by odqahn** [comment]
Cool, thank you for your answer! 

I'll just wait and see how they improve on this and I guess I'll keep reading about all that. Seems what you are doing is gonna bring a better support of old games to Linux (and hopefully Mac, if they keep on working on gptk) than Windows.
