### ISSUE TITLE
State cache not really being created ?

### ISSUE THREAD

**Issue by triatomic** [AlpyneDreams/d8vk#189]
### Software information
Game: c&c generals zerohour
### System information
- GPU: 1060
- Driver: 528.24.0
- OS: Windows 11 22h2 (22621.2428)
- DXVK version: d8vk-v1.0

I can see cache being compiled with dxvk hud enabled ingame.

Issue: 
Before creating the cahce file myself, the game with d8vk doesn't even create the cache file; after creating the file in a global dir (i have DXVK enviro variables setup) local cache setup is the same.
the cache content is only:
`DXVK       `

![procmon generals](https://github.com/AlpyneDreams/d8vk/assets/32312517/e34d4ae9-b8f0-46db-83df-cb54b543cff4)

**Comment by Blisto91** [comment]
The state cache file is rarely used since the introduction of graphics pipeline library so that is expected. (At least for dxvk, but I assume the same for d8vk)

Edit: note the state cache file actually never contained the actual shader cache. Just some extra info dxvk used along with the driver cache

**Comment by triatomic** [comment]
there is a clear difference in cache content between DXVK and d8vk; moreover if i don't create the file myself it doesn't write the file in the specified directory (check attached image in OP)

**Comment by WinterSnowfall** [comment]
@Blisto91 is correct: d8vk uses GPL in the latest release, therefore it's your driver cache that will fill up, not the cache file. At this point the dxvk cache is used as a fallback in the few situations where GPL can't be used.

> there is a clear difference in cache content between DXVK and d8vk; moreover if i don't create the file myself it doesn't write the file in the specified directory (check attached image in OP)

Please understand that you can't compare apples to oranges. D3D8 games in general are not typically shader heavy, so not having a cache at all, or having a rather empty cache is not uncommon, it is normal.

If you are using d3d8to9 + dxvk and comparing caches with d8vk, I'd also typically expect them to be different since d3d8to9 does a lot of disassembly and shaderop black magic.

That being said, I have to ask: what is the actual problem here? Is the game misbehaving in some way?

**Comment by triatomic** [comment]
No, the game is not misbehaving (but it will be recompiling the same shaders in the same instance) & is v1.0 considered the latest version ?

**Comment by WinterSnowfall** [comment]
> No, the game is not misbehaving (but it will be recompiling the same shaders in the same instance)

There are possible situations with fixed function shaders where GPL or the dxvk cache won't do much (because they end up considered as different versions IIRC). But that's a shared problem with d3d9 dxvk and requires quite a bit of redesign to overcome. More details here: https://github.com/doitsujin/dxvk/issues/3534

> is v1.0 considered the latest version ?

At this point in time, yes. You are free to compile from main if you want "the bleeding edge", however note there are still some pending issues at the moment (I've PRed some fixes, waiting for them to be merged).
