### ISSUE TITLE
[Question] DX5-7, OGL

### ISSUE THREAD

**Issue by UserGit-2021** [AlpyneDreams/d8vk#192]
Will there be support for DX5-7?
And a question about OpenGL. Do you have plans for development for modern OS?
For example: Increase the screen resolution to 4K, some older games do not have 4K support or have a small HUD.

**Comment by WinterSnowfall** [comment]
> Will there be support for DX5-7? 

... the project is called d**8**vk for a reason. Also note that while upstream (dxvk) devs are open to merging d3d8 support, and the process is ongoing, they are similarly opposed to merging anything that drops into ddraw territory (which would be d3d7 and below) because of the huge technical burden that would bring.

Even if Alpyne is willing to experiment with the concept of earlier d3d API translation outside of d8vk (and I'd be happy to help here), don't expect upstream support for anything below d3d8.

> And a question about OpenGL.

This is entirely out of scope in the current context. d8vk translates d3d8 to Vulkan and these are the only APIs involved. If you're looking for OpenGL to Vulkan translation, try [Zink](https://docs.mesa3d.org/drivers/zink.html).

> For example: Increase the screen resolution to 4K, some older games do not have 4K support or have a small HUD.

This has been discussed upstream in the context of d3d, but deemed out of scope for dxvk. See: https://github.com/doitsujin/dxvk/issues/3699 .

**Comment by pm4rcin** [comment]
@AlpyneDreams sorry for asking here but what about your branch d3d7? Are you going to develop the fork of DXVK or is it abandoned now? I know d3d8 is now upstream dxvk but I'm wondering if you're going to work on d3d7 or not? If not then maybe archive the repo?

**Comment by WinterSnowfall** [comment]
The repo will be archived once all the pending issues have been resolved or migrated. As for d3d7, that's TBD at this point.
