### ISSUE TITLE
BUG: No FMVs when trying The Thing with D8VK and GE-Proton

### ISSUE THREAD

**Issue by btegs** [AlpyneDreams/d8vk#194]
### Software information
The Thing

### System information
- GPU: AMD Radeon 6900XT
- Driver: Mesa 23.2.1
- Wine version:  GE-Proton8-25
- DXVK version: d8vk 1.0

The Thing (from myabandonware.com) is a DirectX 8 game that also has some FMV cutscenes. When trying to add this game as a non-steam game and using the [recent GE Proton](https://github.com/GloriousEggroll/proton-ge-custom/releases) with D8VK included, the main menu and FMV scenes do not work.

I did change my launch commands to `PROTON_ENABLE_D8VK=1 %command%` and noticed this immediately. I believe this may be a GE Proton or a Proton issue in general since the video codecs may be missing. When GE added D8VK as part of the 8-24 version, he also included some mpeg codecs.

I was curious if anyone else here has tried to get this game's FMVs to run.

**Comment by WinterSnowfall** [comment]
First off, please do not raise issues here using anything other than official retail or digital versions of the game, ideally with the latest available official patches applied... aside from it being, at best, a grey area practice that we can't condone, there's really no accounting for irregularities in your findings due to the game's questionable provenance.

> I believe this may be a GE Proton or a Proton issue in general since the video codecs may be missing.

Please try to rule this out yourself, ideally before raising an issue here. We can't do anything to help with general Wine/Proton issues and this isn't a good place to discuss them.

A fair question to ask yourself beforehand is does the game work properly on native drivers (Windows) or with WineD3D? If it does, then it's potentially a problem we can look into.

That being said, GE Proton I believe pulls the main branch of d8vk which is currently known to be broken in some cases. The problem may simply go away if you use the 1.0 version of d8vk. 

Attaching logs and a trace is also paramount to debugging, so please provide all the relevant details requested on the issue template.

**Comment by btegs** [comment]
@WinterSnowfall 

> First off, please do not raise issues here using anything other than official retail or digital versions of the game, ideally with the latest available official patches applied... aside from it being, at best, a grey area practice that we can't condone, there's really no accounting for irregularities in your findings due to the game's questionable provenance.

There is a prior issue report for House of the Dead III, which is also an older game not sold on digital storefronts and had a prior release. Since this project is dedicated to DirectX 8, it is expeceted that many of these are not on modern storefronts and old CDs have to be tracked down.

> That being said, GE Proton I believe pulls the main branch of d8vk which is currently known to be broken in some cases. The problem may simply go away if you use the 1.0 version of d8vk.

It seems that someone on the GE github has started looking into mpeg related decoders for older games which is nice as d8vk needs to be tested more. The first one is Crimson Skies (also not on Steam like The Thing) which is a great start.

**Comment by WinterSnowfall** [comment]
> Since this project is dedicated to DirectX 8, it is expeceted that many of these are not on modern storefronts and old CDs have to be tracked down.

Second hand retail copies are a valid source, but thankfully there are also a surprising amount of d3d8 titles available digitally. Not nearly enough, sadly, but it could be a lot worse. There's [a PCGW list](https://www.pcgamingwiki.com/wiki/List_of_Direct3D_8_games) I'm helping maintain, among other things.

>  as d8vk needs to be tested more.

We appreciate additional testing and reports in case of issues, of course. Note that prior to d8vk's 1.0 release we have done quite an extensive round of testing, including a lot of rather obscure titles (pun intended, "Obscure" is also a d3d8 game). [See this former "issue"](https://github.com/AlpyneDreams/d8vk/issues/75) for reference.

Giving games a go on Windows when Wine/Proton issues are a blocker is also an option. In some cases it actually helps ensure no other factors are contributing to noticed irregularities.
