### ISSUE TITLE
Castle Strike invisible cursor

### ISSUE THREAD

**Issue by Blisto91** [AlpyneDreams/d8vk#202]
Cursor doesn't show when using d8vk. Works with wined3d

### Software information
Castle Strike

### System information
- GPU: RX 6800
- Driver: mesa main
- Wine version: 9.1
- DXVK version: One of @WinterSnowfall builds :frog:

### Apitrace file(s)
[Castlestrike.trace.tar.gz](https://github.com/AlpyneDreams/d8vk/files/14210999/Castlestrike.trace.tar.gz)

### Log files
[Castlestrike_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/14210973/Castlestrike_d3d9.log)

**Comment by WinterSnowfall** [comment]
The game attempts to create a 64 x 64 cursor even when using the hardware cursor config option in the settings menu. I've thrown [my PR](https://github.com/doitsujin/dxvk/pull/3841) at it, which can handle that, but there's still no cursor although there's no explicit failure anywhere.

In terms of API calls, the cursor is created with an initial call to SetCursorProperties(), followed by a call to SetCursorPosition() on every frame, so it's definitely attempting to use a d3d hardware cursor.

I'll see if I can figure out what we're doing wrong here.

**Comment by WinterSnowfall** [comment]
Since none of the hardware cursor logic seems to fail, yet we have no cursor, I had the idea of dumping the content of the cursor bitmap to see if there's anything odd going on. And there is something odd indeed.


Here is a dump of a 64 x 64 cursor that works: [DungeonSiege2.txt](https://github.com/AlpyneDreams/d8vk/files/14215149/DungeonSiege2.txt)

And here is the dump of the 64 x 64 cursor that this game is trying to create: [CastleStrike.txt](https://github.com/AlpyneDreams/d8vk/files/14215153/CastleStrike.txt)

This is supposed to be ARGB (little endian, I guess?), which makes sense for the cursor that works, but doesn't make any sense at all for what Castle Strike is trying to use. I'm at a loss.

**Comment by WinterSnowfall** [comment]
Did a bit more investigation and found out that:
- The game does indeed use the above d3d calls when hardware cursor support is enabled (there's a toggle in the options menu for that). The same calls don't show up at all when hardware cursor support is disabled.
- Above d3d calls (when hardware cursor support is enabled) don't seem to work properly. Even WineD3D uses a software cursor in this case, which is shown from the very first frame and always stays visible, thus not responding to any of the d3d ShowCursor() calls and simply doing its software cursor things.
- The game might have broken hardware cursor support and it unfortunately relies on true software cursors as a fallback (aka capturing WM_MOUSEMOVE events and all that).

Fully implementing a software cursor would be an absolute pain, so I think we should simply recommend disabling hardware cursor support for the time. To be fair the game's use of the feature isn't exactly working properly, so half the story here is a game bug as well.

**Comment by WinterSnowfall** [comment]
As a final note, I did in fact get the cursor to show with d8vk... by spamming calls to ::ShowCursor(TRUE). Not exactly a proper fix or something one can work around without getting deep into win32 land. But at least now the situation makes more sense, since the d3d cursor creation logic is proven to work just fine. The game just doesn't know what to do with it. It's mixing both d3d and win32 calls with a hardware cursor, so my previous assessment stands. 

It will need a full software cursor implementation to handle all the win32 madness properly, and mind you this is true for its "hardware cursor" mode, which is nothing of the sort. Unticking that horribly broken option that shouldn't exist in the first place makes it work on win32 exclusively and there are no issues there.

**Comment by WinterSnowfall** [comment]
~~I have sort of fixed it, with some minor caveats on Windows. We can close this once https://github.com/doitsujin/dxvk/pull/3841 is merged upstream and we rebase. Will add a config entry for it later to actually enable the workaround with the game.~~

Nevermind. Proper software cursor support is needed here and K0bin is working on it, which should fix this game along with Dungeon Siege 2.

**Comment by Blisto91** [comment]
Castle Strike? More like. Cursor Strike

**Comment by WinterSnowfall** [comment]
> Nevermind. Proper software cursor support is needed here and K0bin is working on it, which should fix this game along with Dungeon Siege 2.

My name must be K0bin, because I am working on it :stuck_out_tongue_winking_eye: . Should also be properly fixed by https://github.com/doitsujin/dxvk/pull/4302.
