### ISSUE TITLE
[Generic Meta-Question]

### ISSUE THREAD

**Issue by iamhumanipromise** [AlpyneDreams/d8vk#203]
I'm quite possibly at the peak of stupidity. Why isn't this project in the Arch, Debian repos? Why did I accidentally stumble upon it while looking for Windows package managers? Silliness aside: 

This seems like a wonderful project and I'm excited to switch back to my CachyOS partition to unwind and play some games tonight; see what works and what doesn't. 

Do you think this will have the potential to become something like "Gallium 8" to provide DX8 over OpenGL 2.0 and higher; Vulkan 1.0 and higher (something like that)? 

Man: the Steam Deck having this by default would be simply amazing. 

Also wondering if the DDrawCompat project had anything to offer for DirectX1-7 over DXVK8? Or each being its own implementation, etc? Seems like there is good overlapping project goals: [DDrawCompat]( https://github.com/narzoul/DDrawCompat)

You are all legends.

**Comment by WinterSnowfall** [comment]
[Generic Meta-Answer (hopefully)]

> Why isn't this project in the Arch, Debian repos?

Because d8vk doesn't offer a native version yet, nor would there be much use in it. Unless you know anyone wanting to port d3d8 games to Linux. But it's available in other places, such as winetricks and the like.

> Do you think this will have the potential to become something like "Gallium 8" to provide DX8 over OpenGL 2.0 and higher; Vulkan 1.0 and higher (something like that)?

That's a weird comparison, since d8vk has nothing to do with Gallium or Mesa in general - it's a complement, or rather an addition if you will, to [dxvk](https://github.com/doitsujin/dxvk)'s d3d9 backend. You'll need hardware support for Vulkan 1.3 to use it, same as dxvk. We don't target OpenGL at all, only d3d8 over Vulkan.
 
> Man: the Steam Deck having this by default would be simply amazing.

An effort to merge d8vk into dxvk is currently in progress, after which you should indeed get it by default on the Steam Deck. Don't get too excited though, since it's bound to take a while until it's finalized.

> Also wondering if the DDrawCompat project had anything to offer for DirectX1-7 over DXVK8? Or each being its own implementation, etc? Seems like there is good overlapping project goals: [DDrawCompat](https://github.com/narzoul/DDrawCompat)

d8vk is solely focused on supporting d3d8 games, as the naming implies. By extension, dxvk doesn't plan to offer direct support for anything below d3d8 (to come with the above mentioned merge). That being said, projects that translate ddraw & d3d1-7 to d3d9 (or 11) have been known to work well in conjunction with dxvk, but the chances of ever having "one project to rule them all" are rather slim to none.
