### ISSUE TITLE
Bug c&c generals 

### ISSUE THREAD

**Issue by Azedin1111** [AlpyneDreams/d8vk#214]
![Screenshot_2024-06-20-01-03-52-544_com ludashi benchmark](https://github.com/AlpyneDreams/d8vk/assets/114381457/12cfc78d-9660-41c7-b212-5426b38f4a5e)
Dxvk dv

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-20-01-42-41-031_com ludashi benchmark](https://github.com/AlpyneDreams/d8vk/assets/114381457/465e64d8-5e5a-4e2b-9068-4146432a0629)

**Comment by Azedin1111** [comment]
Bug
![Screenshot_2024-06-20-01-42-41-031_com ludashi benchmark](https://github.com/AlpyneDreams/d8vk/assets/114381457/76dd2296-639a-4d4e-ab09-caf2f1e98958)

**Comment by WinterSnowfall** [comment]
The game looks and works fine over here (both with d8vk and d3d8to9 + dxvk).

Please fill in the issue template, as it's rather important:
- to know what you're running it on
- to have a trace so we can easily reproduce the problem (or not)

Also AFAIK the game doesn't support widescreen out of the box, so I'm guessing there's some modding involved?

P.S.: You're not actually using d8vk in any of the above screenshots, since d3d9 is listed as the API.

**Comment by Azedin1111** [comment]
d3d8to9 +Dxvk dev on bug

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-23-15-05-41-373_com ludashi benchmark](https://github.com/AlpyneDreams/d8vk/assets/114381457/1aa2f962-949b-461a-8890-4fc4c9b73b88)

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-23-15-08-26-886_com android chrome-edit](https://github.com/AlpyneDreams/d8vk/assets/114381457/e8998ef4-dd04-4328-a9da-48f81a016ce6)
Bug

**Comment by WinterSnowfall** [comment]
@Blisto91 has reproduced the bug with latest dxvk, however there's not much to do about it at the moment on d8vk side. Please stick to using dxvk 2.3.1 (release) for now if you insist on d3d8to9 + dxvk, since that reportedly works fine.

P.S.: Feel free to open a dxvk issue about it.
