### ISSUE TITLE
D3D8-specific workarounds already in upstream

### ISSUE THREAD

**Issue by AlpyneDreams** [AlpyneDreams/d8vk#40]
There are already some workarounds for d3d8to9 in config.cpp that could be put under the d3d8 section. A few of them might not be necessary for d8vk. There's also some minor d9vk fixes for d3d8 games. 

- [x] [ToEE](https://github.com/AlpyneDreams/d8vk/blob/1ee2743a34880941f6c7281e33363e9b65962ec0/src/util/config/config.cpp#L404)
- [x] [Scrapland](https://github.com/AlpyneDreams/d8vk/blob/1ee2743a34880941f6c7281e33363e9b65962ec0/src/util/config/config.cpp#L553)
- [x] [Freelancer](https://github.com/doitsujin/dxvk/commit/27b9736626f42c95b1e5efd02576d3af6068ed6a)
- [x] [Exotic texture format for SW: Republic Commando](https://github.com/doitsujin/dxvk/issues/1430#issuecomment-584254295)

Thanks to WinterSnowfall for the heads up

**Comment by WinterSnowfall** [comment]
Not sure if it's entirely relevant, but this was also done for a d3d8 game (Evil Genius): https://github.com/doitsujin/dxvk/commit/acb3cda1dcbddccd4601f91ab02ddc21856f1409

I've gone through everything I've reported, and this seems to be all the d3d8-related stuff.

Edit: Nevermind about Evil Genius - turns out it's a d3d9 game actually.

**Comment by AlpyneDreams** [comment]
Pending: [[d3d9] Implement converter for W11V11U10](https://github.com/doitsujin/dxvk/pull/3032).
I will probably just rebase when it's merged.

Edit: Probably done now.
